python main.py --data_dir="../IXI" \
               --loss="1*MSE" \
               --save="firefly" \
               --modal1="T1" \
               --modal2="DTI" \
               --model="demo" \
               --train_ratio=0.8 \
               --val_ratio=0.05 \
               --test_ratio=0.15 \
               --epochs=200 \
               --batch_size=1 \
               --lr=1e-3 \
               --pre_train="./experiment/firefly/model/model_best.pt" \
               --n_GPU=1 \
               --gpu_ids 0 \
               --test_only