python main.py --data_dir="../IXI_2d" \
               --loss="1*L1" \
               --save="test111" \
               --modal1="DTI" \
               --modal2="DTI" \
               --model="test1" \
               --train_ratio=0.8 \
               --val_ratio=0.05 \
               --test_ratio=0.15 \
               --epochs=200 \
               --batch_size=1 \
               --lr=1e-3 \
               --modal_num=1 \
               --pre_train="./experiment/test_single_modality_DTI/model/model_best.pt" \
               --n_GPU=1 \
               --gpu_ids 0 \
               --test_only