python main.py --data_dir="../IXI_2d" \
               --loss="1*L1" \
               --save="test_fusion_modality" \
               --modal1="T1" \
               --modal2="DTI" \
               --model="test1" \
               --train_ratio=0.8 \
               --val_ratio=0.05 \
               --test_ratio=0.15 \
               --epochs=200 \
               --batch_size=16 \
               --lr=1e-2 \
               --pre_train=None \
               --modal_num=1 \
               --n_GPUs=1 \
               --gpu_ids 1